config/routes.rb
Rails.application.routes.draw do


  root 'main#tab1'

  get 'login', to: 'sessions#new', as: 'login'

  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'main/filter'

  post 'main/filter'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'reports/customers'

  get 'reports/products'

  get 'reports/store_transactions'

  get 'accounts/index'

  get 'product_colors/index'

  get 'product_sizes/index'

  get 'store_products/index'

  get 'main/update_cart'

  post 'main/update_cart'

  get 'main/checkout'

  post 'main/checkout'

  get 'main/cart'

  get 'main/search'

  post 'main/search'

  post 'main/buy'

  resources :store_products
  resources :promotions
  resources :sessions
  resources :store_transactions
  resources :product_sizes
  resources :product_colors
  resources :product_types
  resources :products
  resources :appointments
  resources :transactions
  resources :reviews
  resources :images
  resources :barber_images
  resources :follows
  resources :customers
  resources :barbers
  resources :accounts

  get 'main/tab1'

  get 'main/tab2'

  get 'main/tab3'

  get 'main/tab4'

  get 'main/help'

  get 'main/privacy'

  #get 'home/index'

  #get 'home/about'

  #get 'home/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :lastName, presence: true
  validates :firstName, presence: true
  validates :phoneNumber, presence: true, uniqueness: true, numericality: true
  #validates :isBarber, presence: true
  validates :city, presence: true
  #validates :username, presence: true, uniqueness: true
  has_secure_password


end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/barber.rb
class Barber < ApplicationRecord
  belongs_to :email
  validates :charge, presence: true, numericality: true
  validates :description, length:{:is => 150}
end

app/models/barber_image.rb
class BarberImage < ApplicationRecord
  belongs_to :customerID
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :customerID
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageGroupID
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :productColor
  has_one :productSize
  validates :productPrice, presence: true, numericality: true
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  validates :color, presence: true
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  validates :size, presence: true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  validates :type, presence: true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
  validates :subject, presence: true
  validates :body, presence: true
  validates :rating, presence: true
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  validates :imgurl, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :product_type, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:type)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.erb
<%= form_with(model: product_type, local: true) do |form| %>
  <% if product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% product_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :product_type_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing Product Type</h1>

<%= render 'form', product_type: @product_type %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Types</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.type %></td>
        <td><%= link_to 'Show', product_type %></td>
        <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
        <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New Product Type</h1>

<%= render 'form', product_type: @product_type %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @product_type.type %>
</p>

<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>