config/routes.rb
Rails.application.routes.draw do


  root 'main#tab1'

  get 'login', to: 'sessions#new', as: 'login'

  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'main/filter'

  post 'main/filter'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'reports/customers'

  get 'reports/products'

  get 'reports/store_transactions'

  get 'accounts/index'

  get 'product_colors/index'

  get 'product_sizes/index'

  get 'store_products/index'

  get 'main/update_cart'

  post 'main/update_cart'

  get 'main/checkout'

  post 'main/checkout'

  get 'main/cart'

  get 'main/search'

  post 'main/search'

  post 'main/buy'

  resources :store_products
  resources :promotions
  resources :sessions
  resources :store_transactions
  resources :product_sizes
  resources :product_colors
  resources :product_types
  resources :products
  resources :appointments
  resources :transactions
  resources :reviews
  resources :images
  resources :barber_images
  resources :follows
  resources :customers
  resources :barbers
  resources :accounts

  get 'main/tab1'

  get 'main/tab2'

  get 'main/tab3'

  get 'main/tab4'

  get 'main/help'

  get 'main/privacy'

  #get 'home/index'

  #get 'home/about'

  #get 'home/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :lastName, presence: true
  validates :firstName, presence: true
  validates :phoneNumber, presence: true, uniqueness: true, numericality: true
  #validates :isBarber, presence: true
  validates :city, presence: true
  #validates :username, presence: true, uniqueness: true
  has_secure_password


end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/barber.rb
class Barber < ApplicationRecord
  belongs_to :email
  validates :charge, presence: true, numericality: true
  validates :description, length:{:is => 150}
end

app/models/barber_image.rb
class BarberImage < ApplicationRecord
  belongs_to :customerID
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :customerID
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageGroupID
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :productColor
  has_one :productSize
  validates :productPrice, presence: true, numericality: true
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  validates :color, presence: true
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  validates :size, presence: true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  validates :type, presence: true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
  validates :subject, presence: true
  validates :body, presence: true
  validates :rating, presence: true
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  validates :imgurl, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :product_type, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/controllers/product_colors_controller.rb
class ProductColorsController < ApplicationController
  before_action :set_product_color, only: [:show, :edit, :update, :destroy]

  # GET /product_colors
  # GET /product_colors.json
  def index
    @product_colors = ProductColor.all
    @selectedTab4 = "is-selected"
  end

  # GET /product_colors/1
  # GET /product_colors/1.json
  def show
  end

  # GET /product_colors/new
  def new
    @product_color = ProductColor.new
  end

  # GET /product_colors/1/edit
  def edit
  end

  # POST /product_colors
  # POST /product_colors.json
  def create
    @product_color = ProductColor.new(product_color_params)

    respond_to do |format|
      if @product_color.save
        format.html { redirect_to @product_color, notice: 'Product color was successfully created.' }
        format.json { render :show, status: :created, location: @product_color }
      else
        format.html { render :new }
        format.json { render json: @product_color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_colors/1
  # PATCH/PUT /product_colors/1.json
  def update
    respond_to do |format|
      if @product_color.update(product_color_params)
        format.html { redirect_to @product_color, notice: 'Product color was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_color }
      else
        format.html { render :edit }
        format.json { render json: @product_color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_colors/1
  # DELETE /product_colors/1.json
  def destroy
    @product_color.destroy
    respond_to do |format|
      format.html { redirect_to product_colors_url, notice: 'Product color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_color
      @product_color = ProductColor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_color_params
      params.require(:product_color).permit(:color)
    end
end

app/helpers/barbers_helper.rb
module BarbersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_colors_helper.rb
module ProductColorsHelper
end

app/views/product_colors/_form.html.erb
<%= form_with(model: product_color, local: true) do |form| %>
  <% if product_color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_color.errors.count, "error") %> prohibited this product_color from being saved:</h2>

      <ul>
      <% product_color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :product_color_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_colors/edit.html.erb
<h1>Editing Product Color</h1>

<%= render 'form', product_color: @product_color %>

<%= link_to 'Show', @product_color %> |
<%= link_to 'Back', product_colors_path %>

app/views/product_colors/index.html.erb
<p id="notice"><%= notice %></p>

<div id="back-button-container"><%= link_to main_tab4_path do %><div id="back-to-reports"><p id="back-label">Back to Reports</p></div><% end %></div>

<div id="index-wrapper">
  <h1>Product Colors</h1>

  <table>
    <thead>
      <tr>
        <th>Color</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @product_colors.each do |product_color| %>
        <tr>
          <td><%= product_color.color %></td>
          <td><%= link_to 'Show', product_color %></td>
          <td><%= link_to 'Edit', edit_product_color_path(product_color) %></td>
          <td><%= link_to 'Destroy', product_color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Product Color', new_product_color_path %>

</div>

app/views/product_colors/new.html.erb
<h1>New Product Color</h1>

<%= render 'form', product_color: @product_color %>

<%= link_to 'Back', product_colors_path %>

app/views/product_colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @product_color.color %>
</p>

<%= link_to 'Edit', edit_product_color_path(@product_color) %> |
<%= link_to 'Back', product_colors_path %>