config/routes.rb
Rails.application.routes.draw do


  root 'main#tab1'

  get 'login', to: 'sessions#new', as: 'login'

  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'main/filter'

  post 'main/filter'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'reports/customers'

  get 'reports/products'

  get 'reports/store_transactions'

  get 'accounts/index'

  get 'product_colors/index'

  get 'product_sizes/index'

  get 'store_products/index'

  get 'main/update_cart'

  post 'main/update_cart'

  get 'main/checkout'

  post 'main/checkout'

  get 'main/cart'

  get 'main/search'

  post 'main/search'

  post 'main/buy'

  resources :store_products
  resources :promotions
  resources :sessions
  resources :store_transactions
  resources :product_sizes
  resources :product_colors
  resources :product_types
  resources :products
  resources :appointments
  resources :transactions
  resources :reviews
  resources :images
  resources :barber_images
  resources :follows
  resources :customers
  resources :barbers
  resources :accounts

  get 'main/tab1'

  get 'main/tab2'

  get 'main/tab3'

  get 'main/tab4'

  get 'main/help'

  get 'main/privacy'

  #get 'home/index'

  #get 'home/about'

  #get 'home/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :lastName, presence: true
  validates :firstName, presence: true
  validates :phoneNumber, presence: true, uniqueness: true, numericality: true
  #validates :isBarber, presence: true
  validates :city, presence: true
  #validates :username, presence: true, uniqueness: true
  has_secure_password


end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/barber.rb
class Barber < ApplicationRecord
  belongs_to :email
  validates :charge, presence: true, numericality: true
  validates :description, length:{:is => 150}
end

app/models/barber_image.rb
class BarberImage < ApplicationRecord
  belongs_to :customerID
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :customerID
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageGroupID
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :productColor
  has_one :productSize
  validates :productPrice, presence: true, numericality: true
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  validates :color, presence: true
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  validates :size, presence: true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  validates :type, presence: true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
  validates :subject, presence: true
  validates :body, presence: true
  validates :rating, presence: true
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  validates :imgurl, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :product_type, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/controllers/barbers_controller.rb
class BarbersController < ApplicationController
  before_action :set_barber, only: [:show, :edit, :update, :destroy]

  # GET /barbers
  # GET /barbers.json
  def index
    @barbers = Barber.all
  end

  # GET /barbers/1
  # GET /barbers/1.json
  def show
  end

  # GET /barbers/new
  def new
    @barber = Barber.new
  end

  # GET /barbers/1/edit
  def edit
  end

  # POST /barbers
  # POST /barbers.json
  def create
    @barber = Barber.new(barber_params)

    respond_to do |format|
      if @barber.save
        format.html { redirect_to @barber, notice: 'Barber was successfully created.' }
        format.json { render :show, status: :created, location: @barber }
      else
        format.html { render :new }
        format.json { render json: @barber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barbers/1
  # PATCH/PUT /barbers/1.json
  def update
    respond_to do |format|
      if @barber.update(barber_params)
        format.html { redirect_to @barber, notice: 'Barber was successfully updated.' }
        format.json { render :show, status: :ok, location: @barber }
      else
        format.html { render :edit }
        format.json { render json: @barber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barbers/1
  # DELETE /barbers/1.json
  def destroy
    @barber.destroy
    respond_to do |format|
      format.html { redirect_to barbers_url, notice: 'Barber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barber
      @barber = Barber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barber_params
      params.require(:barber).permit(:email, :charge, :averageRating, :description, :barberType)
    end
end

app/helpers/barbers_helper.rb
module BarbersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/barbers/_form.html.erb
<%= form_with(model: barber, local: true) do |form| %>
  <% if barber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barber.errors.count, "error") %> prohibited this barber from being saved:</h2>

      <ul>
      <% barber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :barber_email %>
  </div>

  <div class="field">
    <%= form.label :charge %>
    <%= form.number_field :charge, id: :barber_charge %>
  </div>

  <div class="field">
    <%= form.label :averageRating %>
    <%= form.number_field :averageRating, id: :barber_averageRating %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :barber_description %>
  </div>

  <div class="field">
    <%= form.label :barberType %>
    <%= form.check_box :barberType, id: :barber_barberType %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/barbers/edit.html.erb
<h1>Editing Barber</h1>

<%= render 'form', barber: @barber %>

<%= link_to 'Show', @barber %> |
<%= link_to 'Back', barbers_path %>

app/views/barbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Barbers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Charge</th>
      <th>Averagerating</th>
      <th>Description</th>
      <th>Barbertype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barbers.each do |barber| %>
      <tr>
        <td><%= barber.email %></td>
        <td><%= barber.charge %></td>
        <td><%= barber.averageRating %></td>
        <td><%= barber.description %></td>
        <td><%= barber.barberType %></td>
        <td><%= link_to 'Show', barber %></td>
        <td><%= link_to 'Edit', edit_barber_path(barber) %></td>
        <td><%= link_to 'Destroy', barber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barber', new_barber_path %>

app/views/barbers/new.html.erb
<h1>New Barber</h1>

<%= render 'form', barber: @barber %>

<%= link_to 'Back', barbers_path %>

app/views/barbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @barber.email %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @barber.charge %>
</p>

<p>
  <strong>Averagerating:</strong>
  <%= @barber.averageRating %>
</p>

<p>
  <strong>Description:</strong>
  <%= @barber.description %>
</p>

<p>
  <strong>Barbertype:</strong>
  <%= @barber.barberType %>
</p>

<%= link_to 'Edit', edit_barber_path(@barber) %> |
<%= link_to 'Back', barbers_path %>