config/routes.rb
Rails.application.routes.draw do


  root 'main#tab1'

  get 'login', to: 'sessions#new', as: 'login'

  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'main/filter'

  post 'main/filter'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'reports/customers'

  get 'reports/products'

  get 'reports/store_transactions'

  get 'accounts/index'

  get 'product_colors/index'

  get 'product_sizes/index'

  get 'store_products/index'

  get 'main/update_cart'

  post 'main/update_cart'

  get 'main/checkout'

  post 'main/checkout'

  get 'main/cart'

  get 'main/search'

  post 'main/search'

  post 'main/buy'

  resources :store_products
  resources :promotions
  resources :sessions
  resources :store_transactions
  resources :product_sizes
  resources :product_colors
  resources :product_types
  resources :products
  resources :appointments
  resources :transactions
  resources :reviews
  resources :images
  resources :barber_images
  resources :follows
  resources :customers
  resources :barbers
  resources :accounts

  get 'main/tab1'

  get 'main/tab2'

  get 'main/tab3'

  get 'main/tab4'

  get 'main/help'

  get 'main/privacy'

  #get 'home/index'

  #get 'home/about'

  #get 'home/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :lastName, presence: true
  validates :firstName, presence: true
  validates :phoneNumber, presence: true, uniqueness: true, numericality: true
  #validates :isBarber, presence: true
  validates :city, presence: true
  #validates :username, presence: true, uniqueness: true
  has_secure_password


end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/barber.rb
class Barber < ApplicationRecord
  belongs_to :email
  validates :charge, presence: true, numericality: true
  validates :description, length:{:is => 150}
end

app/models/barber_image.rb
class BarberImage < ApplicationRecord
  belongs_to :customerID
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :customerID
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageGroupID
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :productColor
  has_one :productSize
  validates :productPrice, presence: true, numericality: true
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  validates :color, presence: true
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  validates :size, presence: true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  validates :type, presence: true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
  validates :subject, presence: true
  validates :body, presence: true
  validates :rating, presence: true
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  validates :imgurl, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :product_type, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :customerID
  belongs_to :barberID
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:dateTime, :customerID_id, :barberID_id)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dateTime %>
    <%= form.datetime_select :dateTime, id: :transaction_dateTime %>
  </div>

  <div class="field">
    <%= form.label :customerID_id %>
    <%= form.text_field :customerID_id, id: :transaction_customerID_id %>
  </div>

  <div class="field">
    <%= form.label :barberID_id %>
    <%= form.text_field :barberID_id, id: :transaction_barberID_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Datetime</th>
      <th>Customerid</th>
      <th>Barberid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.dateTime %></td>
        <td><%= transaction.customerID %></td>
        <td><%= transaction.barberID %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datetime:</strong>
  <%= @transaction.dateTime %>
</p>

<p>
  <strong>Customerid:</strong>
  <%= @transaction.customerID %>
</p>

<p>
  <strong>Barberid:</strong>
  <%= @transaction.barberID %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>